import "./style.scss";
import "./repository-edit.scss";
import "./navindexfooter.scss";
import "./repository_show.scss";
import "./logged_in.scss"
import "./repo-nav.scss";
import "./issue_show.scss";
import "./repositories_nb.scss";
import "./following.scss";
import "./follower.scss";
import "./code.scss";
import "./pull_request.scss";
import "./public.scss";
import "./projet_setting.scss";
import "./projet_setting.scss";
import "./repo_new.scss";
import "./new_issue.scss";
import "./like.scss";
